dist: xenial

language: rust
sudo: false

cache: cargo

matrix:
  include:
    - rust: stable
    - rust: nightly
    - rust: beta

script:
  - cargo test

addons:
  apt:
    sources:
      - docker-xenial
    packages:
      - docker

branches:
  only:
    - master

notifications:
  webhooks:
    - https://travis-tg.herokuapp.com/u/312348960/force
